version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - authenticationdbdata:/var/lib/mysql
    networks:
      - mynet
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    networks:
      - mynet
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    ports:
    - 5002:5002
    networks:
      - mynet
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mynet

volumes:
  authenticationdbdata:

networks:
  mynet: